//! In-game Valorant chat text expander.
//!
//! The Riot chat HTTP API only sees messages **our overlay** sends. When the
//! player types in the native game chat box, nothing hits our code — so
//! shortcuts would never fire. This module installs a Windows low-level
//! keyboard hook that, while VALORANT is focused and the chat bar is open:
//!   - buffers what is typed
//!   - on Enter (send), expands `sa` / `as` / `<3` / `!t <lang> …` before send
//!
//! Expansion: swallow Enter → clear line → paste expanded text via clipboard
//! (Unicode SendInput was dropping mid-string in Valorant) → Enter.
//! Translate (`!t`) runs on a background thread so the hook never blocks.
//!
//! Valorant keeps the chat bar **open after send** until Escape — so we must
//! keep `chat_open = true` after a send, otherwise the next line is not
//! buffered and shortcuts randomly "stop working".
//!
//! # Staying alive
//!
//! Windows enforces `LowLevelHooksTimeout` (~300 ms by default) on
//! `WH_KEYBOARD_LL` callbacks. On Windows 7+ a hook that overruns it is
//! **silently removed** — no error, no callback, ever again. That is why the
//! shortcuts used to die mid-session and only came back after an app restart.
//! Two things guard against it now:
//!   1. The hook body is cheap: no `OpenProcess`, no allocations. A 150 ms
//!      background poller resolves the foreground process instead.
//!   2. A watchdog probes the hook with a swallowed synthetic keystroke and
//!      reinstalls it when Windows has dropped it.

#![cfg(windows)]

use once_cell::sync::Lazy;
use parking_lot::Mutex;
use std::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, Ordering};
use std::time::{Duration, Instant};

use windows::core::PWSTR;
use windows::Win32::Foundation::{HANDLE, HINSTANCE, HWND, LPARAM, LRESULT, WPARAM};
use windows::Win32::System::DataExchange::{
    CloseClipboard, EmptyClipboard, OpenClipboard, SetClipboardData,
};
use windows::Win32::System::Memory::{GlobalAlloc, GlobalLock, GlobalUnlock, GMEM_MOVEABLE};

/// Win32 clipboard format for UTF-16 text.
const CF_UNICODETEXT: u32 = 13;
use windows::Win32::System::Threading::{
    GetCurrentThreadId, OpenProcess, QueryFullProcessImageNameW, PROCESS_NAME_WIN32,
    PROCESS_QUERY_LIMITED_INFORMATION,
};
use windows::Win32::UI::Input::KeyboardAndMouse::{
    GetAsyncKeyState, GetKeyboardState, SendInput, ToUnicode, INPUT, INPUT_0, INPUT_KEYBOARD,
    KEYBDINPUT, KEYBD_EVENT_FLAGS, KEYEVENTF_KEYUP, KEYEVENTF_UNICODE, VIRTUAL_KEY, VK_A, VK_BACK,
    VK_CONTROL, VK_DELETE, VK_ESCAPE, VK_RETURN, VK_SHIFT, VK_V,
};
use windows::Win32::UI::WindowsAndMessaging::{
    CallNextHookEx, DispatchMessageW, GetForegroundWindow, GetMessageW, GetWindowThreadProcessId,
    PostThreadMessageW, SetWindowsHookExW, TranslateMessage, UnhookWindowsHookEx, HHOOK,
    KBDLLHOOKSTRUCT, MSG, WH_KEYBOARD_LL, WM_KEYDOWN, WM_KEYUP, WM_SYSKEYDOWN, WM_SYSKEYUP,
};

/// LLKHF_INJECTED — key was generated by SendInput / another process.
const LLKHF_INJECTED: u32 = 0x10;

/// `VK_NONAME` (0xFC) — reserved, not bindable in Valorant. Used as the
/// watchdog's liveness probe; our own hook swallows it.
const VK_NONAME: u16 = 0xFC;

/// Posted to the hook thread to make it drop and reinstall the hook.
const WM_REINSTALL_HOOK: u32 = 0x8000 + 71; // WM_APP + 71

/// How long the chat bar may sit untouched before we assume the game closed it.
/// Without this, a stale `chat_open` swallows the *next* Enter as if it were a
/// send, which flips the state machine and silently skips one expansion.
const CHAT_IDLE_TIMEOUT_MS: u64 = 20_000;

/// A callback this recent means Windows still owns the hook — skip the probe.
const HOOK_FRESH_MS: u64 = 5_000;

static STARTED: AtomicBool = AtomicBool::new(false);

/// Thread that owns the hook + its message loop (target for reinstall posts).
static HOOK_THREAD_ID: AtomicU32 = AtomicU32::new(0);
/// Monotonic ms of the last hook callback — the liveness heartbeat.
static LAST_HOOK_MS: AtomicU64 = AtomicU64::new(0);
/// Watchdog probe in flight; the hook swallows `VK_NONAME` while set.
static PROBE_ARMED: AtomicBool = AtomicBool::new(false);
/// Set by the hook when it observes the probe.
static PROBE_SEEN: AtomicBool = AtomicBool::new(false);

/// Foreground pid as of the last poll, and whether it is Valorant. The hook
/// only reads these atomics, so it never touches a process handle.
static FG_PID: AtomicU32 = AtomicU32::new(0);
static FG_IS_VALORANT: AtomicBool = AtomicBool::new(false);

/// Monotonic clock base for the ms timestamps above.
static CLOCK: Lazy<Instant> = Lazy::new(Instant::now);

fn now_ms() -> u64 {
    CLOCK.elapsed().as_millis() as u64
}

struct ExpanderState {
    /// True while the in-game chat bar is open (Enter to open, Escape to close).
    /// Stays true after a successful send — Valorant leaves the bar open.
    chat_open: bool,
    /// Characters typed into the chat bar (best-effort).
    buffer: String,
    /// While we inject keys, ignore them so we don't re-buffer ourselves.
    injecting: bool,
    /// Last time we saw chat-bar activity, for `CHAT_IDLE_TIMEOUT_MS`.
    last_activity_ms: u64,
    /// Escape was pressed mid-injection — drop the pending expansion.
    abort_injection: bool,
}

static STATE: Mutex<ExpanderState> = Mutex::new(ExpanderState {
    chat_open: false,
    buffer: String::new(),
    injecting: false,
    last_activity_ms: 0,
    abort_injection: false,
});

fn needs_expansion(raw: &str) -> bool {
    crate::chat_text::needs_chat_expansion(raw)
}

/// What currently owns keyboard focus, from the hook's point of view.
#[derive(PartialEq, Eq)]
enum Focus {
    Valorant,
    Other,
    /// Focus changed since the last poll — we don't know yet. Neither buffer
    /// nor reset; the poller catches up within ~150 ms.
    Unknown,
}

/// Foreground pid via two cheap user32 calls (no process handle).
fn foreground_pid() -> u32 {
    unsafe {
        let hwnd = GetForegroundWindow();
        if hwnd.0.is_null() {
            return 0;
        }
        let mut pid: u32 = 0;
        GetWindowThreadProcessId(hwnd, Some(&mut pid));
        pid
    }
}

/// Hook-safe focus check: compares the live foreground pid against the one the
/// poller already classified. Must stay allocation- and syscall-light so the
/// callback never trips `LowLevelHooksTimeout`.
fn focus_state() -> Focus {
    let pid = foreground_pid();
    if pid == 0 || pid != FG_PID.load(Ordering::Acquire) {
        return Focus::Unknown;
    }
    if FG_IS_VALORANT.load(Ordering::Relaxed) {
        Focus::Valorant
    } else {
        Focus::Other
    }
}

/// Resolve a pid's image name — the expensive part, kept off the hook thread.
fn pid_is_valorant(pid: u32) -> bool {
    unsafe {
        let Ok(proc) = OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, false, pid) else {
            return false;
        };
        let mut buf = [0u16; 512];
        let mut size = buf.len() as u32;
        let ok = QueryFullProcessImageNameW(
            proc,
            PROCESS_NAME_WIN32,
            PWSTR(buf.as_mut_ptr()),
            &mut size,
        )
        .is_ok();
        let _ = windows::Win32::Foundation::CloseHandle(proc);
        if !ok {
            return false;
        }
        let path = String::from_utf16_lossy(&buf[..size as usize]);
        let name = path.rsplit(['\\', '/']).next().unwrap_or(path.as_str());
        name.eq_ignore_ascii_case("VALORANT-Win64-Shipping.exe")
    }
}

/// Keep `FG_PID` / `FG_IS_VALORANT` current so the hook can stay cheap.
fn start_foreground_poller() {
    std::thread::Builder::new()
        .name("chat-expander-fg".into())
        .spawn(|| loop {
            let pid = foreground_pid();
            if pid != FG_PID.load(Ordering::Relaxed) {
                let is_valorant = pid != 0 && pid_is_valorant(pid);
                // Publish the classification before the pid it belongs to, so a
                // hook that sees this pid also sees the matching flag.
                FG_IS_VALORANT.store(is_valorant, Ordering::Relaxed);
                FG_PID.store(pid, Ordering::Release);
            }
            std::thread::sleep(Duration::from_millis(150));
        })
        .ok();
}

fn shift_down() -> bool {
    unsafe { GetAsyncKeyState(VK_SHIFT.0 as i32) as u16 & 0x8000 != 0 }
}

fn ctrl_down() -> bool {
    unsafe { GetAsyncKeyState(VK_CONTROL.0 as i32) as u16 & 0x8000 != 0 }
}

/// Map a virtual-key to a typed character.
/// Prefer ToUnicode (layout-aware); fall back to basic QWERTY for reliability
/// when ToUnicode returns nothing (common under LL hooks).
fn key_to_char(vk: u32, scan: u32) -> Option<char> {
    unsafe {
        let mut state = [0u8; 256];
        let _ = GetKeyboardState(&mut state);
        if shift_down() {
            state[VK_SHIFT.0 as usize] |= 0x80;
        }
        let mut buf = [0u16; 8];
        let n = ToUnicode(vk, scan, Some(&state), &mut buf, 0);
        if n > 0 {
            let s = String::from_utf16_lossy(&buf[..n as usize]);
            if let Some(c) = s.chars().next().filter(|c| !c.is_control()) {
                return Some(c);
            }
        }
        // ToUnicode can return -1 for dead keys and leave the layout sticky;
        // a second call with space often clears it — ignore result.
        if n < 0 {
            let mut clear = [0u16; 8];
            let _ = ToUnicode(0x20, 0, Some(&state), &mut clear, 0);
        }
    }

    // ASCII fallback (US-ish). Covers sa/as/<3 even when ToUnicode fails.
    let shift = shift_down();
    match vk {
        // 0-9
        0x30..=0x39 => {
            let digits = b"0123456789";
            let shifted = b")!@#$%^&*(";
            let i = (vk - 0x30) as usize;
            Some(if shift {
                shifted[i] as char
            } else {
                digits[i] as char
            })
        }
        // A-Z
        0x41..=0x5A => {
            let base = (b'a' + (vk - 0x41) as u8) as char;
            Some(if shift {
                base.to_ascii_uppercase()
            } else {
                base
            })
        }
        // Space
        0x20 => Some(' '),
        // OEM keys common for `<` `>` `/` etc. (US + some TR layouts)
        0xBC => Some(if shift { '<' } else { ',' }), // VK_OEM_COMMA
        0xBE => Some(if shift { '>' } else { '.' }), // VK_OEM_PERIOD
        0xBF => Some(if shift { '?' } else { '/' }), // VK_OEM_2
        0xBA => Some(if shift { ':' } else { ';' }), // VK_OEM_1
        // VK_OEM_102 — key between LShift and Z on many EU/TR boards (`<` `>`)
        0xE2 => Some(if shift { '>' } else { '<' }),
        // `!` for translate command
        // already covered by shift+1 → '!'
        _ => None,
    }
}

fn send_vk(vk: VIRTUAL_KEY, down: bool) {
    unsafe {
        let flags = if down {
            KEYBD_EVENT_FLAGS(0)
        } else {
            KEYEVENTF_KEYUP
        };
        let input = INPUT {
            r#type: INPUT_KEYBOARD,
            Anonymous: INPUT_0 {
                ki: KEYBDINPUT {
                    wVk: vk,
                    wScan: 0,
                    dwFlags: flags,
                    time: 0,
                    dwExtraInfo: 0,
                },
            },
        };
        let _ = SendInput(&[input], std::mem::size_of::<INPUT>() as i32);
    }
}

fn send_unicode_char(ch: char) {
    // BMP only (our expansions stay in BMP).
    let unit = ch as u16;
    unsafe {
        let down = INPUT {
            r#type: INPUT_KEYBOARD,
            Anonymous: INPUT_0 {
                ki: KEYBDINPUT {
                    wVk: VIRTUAL_KEY(0),
                    wScan: unit,
                    dwFlags: KEYEVENTF_UNICODE,
                    time: 0,
                    dwExtraInfo: 0,
                },
            },
        };
        let up = INPUT {
            r#type: INPUT_KEYBOARD,
            Anonymous: INPUT_0 {
                ki: KEYBDINPUT {
                    wVk: VIRTUAL_KEY(0),
                    wScan: unit,
                    dwFlags: KEYEVENTF_UNICODE | KEYEVENTF_KEYUP,
                    time: 0,
                    dwExtraInfo: 0,
                },
            },
        };
        let _ = SendInput(&[down, up], std::mem::size_of::<INPUT>() as i32);
    }
}

fn send_unicode_string_slow(s: &str) {
    // Fallback only — Valorant often drops mid-string when fed too fast.
    for ch in s.chars() {
        send_unicode_char(ch);
        std::thread::sleep(Duration::from_millis(12));
    }
}

fn tap_key(vk: VIRTUAL_KEY) {
    send_vk(vk, true);
    std::thread::sleep(Duration::from_millis(8));
    send_vk(vk, false);
    std::thread::sleep(Duration::from_millis(8));
}

/// Put Unicode text on the Windows clipboard (CF_UNICODETEXT).
///
/// `OpenClipboard` fails whenever another process holds it — clipboard managers
/// do this constantly — so retry briefly instead of falling straight back to
/// the slow SendInput path that Valorant tends to cut mid-string.
fn set_clipboard_text(text: &str) -> bool {
    unsafe {
        let mut opened = false;
        for attempt in 0..6 {
            if OpenClipboard(HWND::default()).is_ok() {
                opened = true;
                break;
            }
            if attempt < 5 {
                std::thread::sleep(Duration::from_millis(20));
            }
        }
        if !opened {
            tracing::warn!("[ChatExpander] OpenClipboard busy after retries");
            return false;
        }
        let _ = EmptyClipboard();
        let wide: Vec<u16> = text.encode_utf16().chain(std::iter::once(0)).collect();
        let bytes = wide.len() * std::mem::size_of::<u16>();
        let Ok(hmem) = GlobalAlloc(GMEM_MOVEABLE, bytes) else {
            let _ = CloseClipboard();
            return false;
        };
        let ptr = GlobalLock(hmem);
        if ptr.is_null() {
            let _ = CloseClipboard();
            return false;
        }
        std::ptr::copy_nonoverlapping(wide.as_ptr(), ptr as *mut u16, wide.len());
        let _ = GlobalUnlock(hmem);
        // Ownership of hmem transfers to the clipboard on success.
        if SetClipboardData(CF_UNICODETEXT, HANDLE(hmem.0 as _)).is_err() {
            let _ = CloseClipboard();
            return false;
        }
        let _ = CloseClipboard();
        true
    }
}

/// Clear whatever is currently in the chat input line.
fn clear_chat_line(original: &str) {
    // Select-all + delete
    send_vk(VK_CONTROL, true);
    std::thread::sleep(Duration::from_millis(15));
    tap_key(VK_A);
    std::thread::sleep(Duration::from_millis(15));
    send_vk(VK_CONTROL, false);
    std::thread::sleep(Duration::from_millis(15));
    tap_key(VK_DELETE);
    std::thread::sleep(Duration::from_millis(15));

    // Backspace original length (+2) if select-all failed.
    let n = original.chars().count().saturating_add(2).min(64);
    for _ in 0..n {
        send_vk(VK_BACK, true);
        send_vk(VK_BACK, false);
        std::thread::sleep(Duration::from_millis(6));
    }
    std::thread::sleep(Duration::from_millis(20));
}

fn paste_clipboard() {
    send_vk(VK_CONTROL, true);
    std::thread::sleep(Duration::from_millis(15));
    tap_key(VK_V);
    std::thread::sleep(Duration::from_millis(15));
    send_vk(VK_CONTROL, false);
    std::thread::sleep(Duration::from_millis(40));
}

/// Expand (may network for `!t`) then inject into the game chat box.
/// Always runs off the hook thread — never block the keyboard hook.
fn inject_expanded_from_raw(raw: String) {
    std::thread::spawn(move || {
        // Claim the injection slot *before* transforming: `!t` can block on the
        // network for seconds and anything typed meanwhile must not land in the
        // buffer we are about to replace.
        {
            let mut st = STATE.lock();
            st.injecting = true;
            st.abort_injection = false;
            st.buffer.clear();
        }

        let text = crate::chat_text::transform_outgoing_chat(&raw);

        // Escape during a slow transform means the user left the chat bar —
        // typing now would feed the expansion to the game as keybinds.
        {
            let mut st = STATE.lock();
            if st.abort_injection {
                st.injecting = false;
                st.abort_injection = false;
                st.buffer.clear();
                tracing::info!("[ChatExpander] Expansion aborted (Escape)");
                return;
            }
        }

        // Let the swallowed Enter settle; Valorant needs a beat before input.
        std::thread::sleep(Duration::from_millis(50));

        // Wipe short form (`sa`, `<3`, …) so we never get `saSelamun…`.
        clear_chat_line(&raw);

        // Prefer clipboard paste — full string at once, no mid-cut "Selamun A".
        let pasted = if set_clipboard_text(&text) {
            paste_clipboard();
            true
        } else {
            false
        };

        if !pasted {
            tracing::warn!("[ChatExpander] Clipboard paste failed; slow Unicode fallback");
            send_unicode_string_slow(&text);
            std::thread::sleep(Duration::from_millis(30));
        }

        // Send the line.
        std::thread::sleep(Duration::from_millis(40));
        tap_key(VK_RETURN);

        // Keep chat_open — Valorant leaves the bar open after send.
        std::thread::sleep(Duration::from_millis(60));
        let mut st = STATE.lock();
        st.injecting = false;
        st.abort_injection = false;
        st.chat_open = true;
        st.buffer.clear();
        st.last_activity_ms = now_ms();
        tracing::info!(
            "[ChatExpander] Injected {:?} → {:?} (paste={})",
            raw.trim(),
            text,
            pasted
        );
    });
}

unsafe extern "system" fn keyboard_proc(code: i32, wparam: WPARAM, lparam: LPARAM) -> LRESULT {
    if code < 0 {
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    // Heartbeat first: any callback proves Windows has not dropped us.
    LAST_HOOK_MS.store(now_ms(), Ordering::Relaxed);

    let kb = &*(lparam.0 as *const KBDLLHOOKSTRUCT);
    let vk = kb.vkCode;

    // Watchdog liveness probe — must be handled before the injected-key and
    // enabled filters, and swallowed so the game never sees it.
    if vk == VK_NONAME as u32 && PROBE_ARMED.load(Ordering::Relaxed) {
        PROBE_SEEN.store(true, Ordering::Relaxed);
        return LRESULT(1);
    }

    if !crate::chat_text::shortcuts_enabled() {
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    let msg = wparam.0 as u32;
    let is_down = msg == WM_KEYDOWN || msg == WM_SYSKEYDOWN;
    let is_up = msg == WM_KEYUP || msg == WM_SYSKEYUP;
    if !is_down && !is_up {
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    // Ignore synthetic keys (our SendInput + any other injectors).
    let flags = kb.flags.0;
    if flags & LLKHF_INJECTED != 0 {
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    {
        let mut st = STATE.lock();
        if st.injecting {
            // Mid-injection only Escape matters: the user bailed out of the
            // chat bar, so cancel the pending expansion.
            if is_down && vk == VK_ESCAPE.0 as u32 {
                st.abort_injection = true;
                st.chat_open = false;
                st.buffer.clear();
            }
            return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
        }
    }

    // Only key-downs shape the buffer; skipping key-ups halves the work the
    // hook does per keystroke, which is what keeps us under the hook timeout.
    if !is_down {
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    match focus_state() {
        Focus::Valorant => {}
        Focus::Other => {
            let mut st = STATE.lock();
            if st.chat_open || !st.buffer.is_empty() {
                st.chat_open = false;
                st.buffer.clear();
            }
            return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
        }
        Focus::Unknown => return CallNextHookEx(HHOOK::default(), code, wparam, lparam),
    }

    // A mouse click, an alternate chat bind or Valorant's own auto-hide can
    // close the bar without us ever seeing Escape. Time the state out so the
    // next Enter is read as "open" rather than swallowed as a send.
    {
        let mut st = STATE.lock();
        if st.chat_open && now_ms().saturating_sub(st.last_activity_ms) > CHAT_IDLE_TIMEOUT_MS {
            st.chat_open = false;
            st.buffer.clear();
            tracing::debug!("[ChatExpander] Chat idle timeout — assuming closed");
        }
    }

    // Ignore pure modifiers.
    if vk == VK_SHIFT.0 as u32 || vk == VK_CONTROL.0 as u32 {
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    // Escape closes chat.
    if vk == VK_ESCAPE.0 as u32 {
        let mut st = STATE.lock();
        st.chat_open = false;
        st.buffer.clear();
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    // Enter: open / send / expand.
    if vk == VK_RETURN.0 as u32 {
        let mut st = STATE.lock();
        st.last_activity_ms = now_ms();

        if !st.chat_open {
            // Opening the chat bar (first Enter).
            st.chat_open = true;
            st.buffer.clear();
            tracing::debug!("[ChatExpander] Chat opened");
            return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
        }

        // Chat already open → this Enter is a send (or empty close).
        let raw = st.buffer.clone();
        let empty = raw.trim().is_empty();
        drop(st);

        if empty {
            // Empty Enter usually closes chat in Valorant.
            let mut st = STATE.lock();
            st.chat_open = false;
            st.buffer.clear();
            tracing::debug!("[ChatExpander] Empty enter — chat closed");
            return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
        }

        if needs_expansion(&raw) {
            tracing::info!("[ChatExpander] Expanding: {:?}", raw.trim());
            // Swallow Enter; background thread will expand + re-send.
            // chat_open stays true after inject.
            inject_expanded_from_raw(raw);
            return LRESULT(1);
        }

        // Normal message: let Enter through, keep chat open for the next line.
        let mut st = STATE.lock();
        st.buffer.clear();
        st.chat_open = true;
        tracing::debug!("[ChatExpander] Normal send, chat stays open");
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    // Buffer while chat is open.
    {
        let mut st = STATE.lock();
        if st.chat_open {
            st.last_activity_ms = now_ms();
            if vk == VK_BACK.0 as u32 {
                st.buffer.pop();
            } else if !ctrl_down() {
                if let Some(ch) = key_to_char(vk, kb.scanCode) {
                    // Cap buffer so a stuck-open state can't grow forever.
                    if st.buffer.len() < 500 {
                        st.buffer.push(ch);
                    }
                }
            }
        }
    }

    CallNextHookEx(HHOOK::default(), code, wparam, lparam)
}

/// Install the low-level hook. Must run on the thread that pumps messages.
unsafe fn install_hook() -> Option<HHOOK> {
    match SetWindowsHookExW(WH_KEYBOARD_LL, Some(keyboard_proc), HINSTANCE::default(), 0) {
        Ok(h) => Some(h),
        Err(e) => {
            tracing::error!("[ChatExpander] SetWindowsHookEx failed: {}", e);
            None
        }
    }
}

/// Ask the hook thread to drop and reinstall its hook.
fn request_reinstall() {
    let tid = HOOK_THREAD_ID.load(Ordering::Relaxed);
    if tid == 0 {
        return;
    }
    unsafe {
        let _ = PostThreadMessageW(tid, WM_REINSTALL_HOOK, WPARAM(0), LPARAM(0));
    }
}

/// Inject a reserved, unbindable key and check whether our own hook sees it.
/// The hook swallows the probe, so Valorant never receives it.
fn hook_alive() -> bool {
    PROBE_SEEN.store(false, Ordering::Relaxed);
    PROBE_ARMED.store(true, Ordering::Relaxed);

    send_vk(VIRTUAL_KEY(VK_NONAME), true);
    send_vk(VIRTUAL_KEY(VK_NONAME), false);

    let mut alive = false;
    for _ in 0..20 {
        std::thread::sleep(Duration::from_millis(10));
        if PROBE_SEEN.load(Ordering::Relaxed) {
            alive = true;
            break;
        }
    }

    PROBE_ARMED.store(false, Ordering::Relaxed);
    alive
}

/// Detect and recover from Windows silently unhooking us.
fn start_hook_watchdog() {
    /// Backoff bounds for the idle probe: tight after trouble, relaxed while
    /// the hook keeps proving itself healthy.
    const MIN_INTERVAL: Duration = Duration::from_secs(3);
    const MAX_INTERVAL: Duration = Duration::from_secs(15);

    std::thread::Builder::new()
        .name("chat-expander-watchdog".into())
        .spawn(|| {
            let mut interval = MIN_INTERVAL;
            loop {
                std::thread::sleep(interval);

                if !crate::chat_text::shortcuts_enabled() {
                    continue;
                }
                // The probe is a synthetic keystroke — only fire it while Valorant
                // owns input, so we never poke other apps or defeat idle timers.
                if !FG_IS_VALORANT.load(Ordering::Relaxed) {
                    continue;
                }
                // Don't interleave a probe with an expansion in flight.
                if STATE.lock().injecting {
                    continue;
                }
                // A recent callback already proves the hook is alive.
                if now_ms().saturating_sub(LAST_HOOK_MS.load(Ordering::Relaxed)) < HOOK_FRESH_MS {
                    continue;
                }
                if hook_alive() {
                    interval = (interval * 2).min(MAX_INTERVAL);
                    continue;
                }

                interval = MIN_INTERVAL;
                tracing::warn!(
                    "[ChatExpander] Keyboard hook is gone (LowLevelHooksTimeout?) — reinstalling"
                );
                request_reinstall();

                // The chat bar state is unknowable across a hook outage.
                let mut st = STATE.lock();
                st.chat_open = false;
                st.buffer.clear();
            }
        })
        .ok();
}

/// Start the low-level keyboard hook on a dedicated message-loop thread,
/// plus the foreground poller and the hook watchdog.
pub fn start() {
    if STARTED.swap(true, Ordering::SeqCst) {
        return;
    }

    Lazy::force(&CLOCK);
    LAST_HOOK_MS.store(now_ms(), Ordering::Relaxed);
    start_foreground_poller();

    std::thread::Builder::new()
        .name("chat-expander".into())
        .spawn(|| unsafe {
            HOOK_THREAD_ID.store(GetCurrentThreadId(), Ordering::Relaxed);

            let mut hook = install_hook();
            if hook.is_some() {
                tracing::info!("[ChatExpander] In-game sa/as/<3/!t expander active");
            } else {
                // Keep the loop alive anyway — the watchdog will retry.
                tracing::error!("[ChatExpander] Initial hook install failed; watchdog will retry");
            }

            start_hook_watchdog();

            let mut msg = MSG::default();
            loop {
                let res = GetMessageW(&mut msg, HWND::default(), 0, 0).0;
                if res == -1 {
                    // Transient error — don't spin the CPU, don't quit.
                    std::thread::sleep(Duration::from_millis(50));
                    continue;
                }
                if res == 0 {
                    break; // WM_QUIT
                }

                if msg.message == WM_REINSTALL_HOOK {
                    if let Some(h) = hook.take() {
                        let _ = UnhookWindowsHookEx(h);
                    }
                    hook = install_hook();
                    if hook.is_some() {
                        tracing::info!("[ChatExpander] Keyboard hook reinstalled");
                        LAST_HOOK_MS.store(now_ms(), Ordering::Relaxed);
                    }
                    continue;
                }

                let _ = TranslateMessage(&msg);
                DispatchMessageW(&msg);
            }

            if let Some(h) = hook.take() {
                let _ = UnhookWindowsHookEx(h);
            }
            STARTED.store(false, Ordering::SeqCst);
        })
        .ok();
}

/// Clear buffered chat state when the feature is toggled off. The hook itself
/// stays installed and gates on `chat_text::shortcuts_enabled()`, so the
/// watchdog keeps it healthy for when the user turns shortcuts back on.
pub fn on_enabled_changed(on: bool) {
    let mut st = STATE.lock();
    st.chat_open = false;
    st.buffer.clear();
    if !on && st.injecting {
        st.abort_injection = true;
    }
}
