//! In-game Valorant chat text expander.
//!
//! The Riot chat HTTP API only sees messages **our overlay** sends. When the
//! player types in the native game chat box, nothing hits our code — so
//! shortcuts would never fire. This module installs a Windows low-level
//! keyboard hook that, while VALORANT is focused and the chat bar is open:
//!   - buffers what is typed
//!   - on Enter (send), expands `sa` / `as` / `<3` / agent tags before send
//!
//! Expansion: swallow Enter (down **and** matching up) → Ctrl+A / Ctrl+C the
//! real chat line (the hook buffer is ASCII-only — `ToUnicode` times out the
//! hook, so TR letters never land in it) → transform → clear line → paste
//! expanded text via clipboard (Unicode SendInput was dropping mid-string in
//! Valorant) → Enter. Expansion runs on a background thread so the
//! hook never blocks.
//!
//! Valorant keeps the chat bar **open after send** until Escape — so we must
//! keep `chat_open = true` after a send, otherwise the next line is not
//! buffered and shortcuts randomly "stop working".
//!
//! # Reliability notes
//!
//! - Swallowing only Enter **keydown** left the real **keyup** free to reach
//!   Valorant; the game sometimes treated that as a send of the short form
//!   (`sa`) before our inject thread finished. Both edges are suppressed for
//!   the expansion window.
//! - `Focus::Unknown` (foreground poller lag) used to drop keystrokes entirely,
//!   so short messages like `sa` intermittently never buffered. While the chat
//!   bar is already open we keep buffering through Unknown / IME / overlays.
//! - Paste + send pacing is intentionally slower than a human mash — Valorant
//!   drops clipboard paste / mid-string input when the inject is too tight.
//! - A short idle timeout used to treat "chat left open between rounds" as
//!   closed. The next `sa` was not buffered and went out raw. Held gameplay
//!   keys (WASD auto-repeat) are the signal that chat actually closed.
//! - After a match Valorant tears down the chat widget. If `chat_open` stayed
//!   true the next Enter looked like a send; if it was already false,
//!   `Focus::Unknown` (exclusive-fullscreen null HWND, or the poller stuck on
//!   `FG_NEUTRAL` because it only reclassified on pid change) refused to
//!   re-arm the bar — shortcuts died until app restart.

//! # Staying alive
//!
//! Windows enforces `LowLevelHooksTimeout` (~300 ms by default) on
//! `WH_KEYBOARD_LL` callbacks. On Windows 7+ a hook that overruns it is
//! **silently removed** — no error, no callback, ever again. That is why the
//! shortcuts used to die mid-session and only came back after an app restart.
//! Guards:
//!   1. The hook body is cheap: no `OpenProcess`, no `ToUnicode` / IME, no
//!      rule-table clones. A ~80 ms background poller resolves focus instead.
//!   2. A watchdog compares physical key transitions (`GetAsyncKeyState`)
//!      against hook heartbeats. SendInput probes are not used — Vanguard
//!      often starts blocking synthetic keys mid-session, which made the
//!      old probe look dead and reset chat state every few seconds.
//!   3. Recovery recycles the **whole hook thread**. Reinstalling on the
//!      same thread after a silent unhook frequently never fires again.

#![cfg(windows)]

use once_cell::sync::Lazy;
use parking_lot::Mutex;
use std::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, AtomicUsize, Ordering};
use std::time::{Duration, Instant};

use windows::core::PWSTR;
use windows::Win32::Foundation::{BOOL, HANDLE, HGLOBAL, HINSTANCE, HWND, LPARAM, LRESULT, WPARAM};
use windows::Win32::System::DataExchange::{
    CloseClipboard, EmptyClipboard, GetClipboardData, OpenClipboard, SetClipboardData,
};
use windows::Win32::System::Memory::{GlobalAlloc, GlobalLock, GlobalUnlock, GMEM_MOVEABLE};

/// Win32 clipboard format for UTF-16 text.
const CF_UNICODETEXT: u32 = 13;
use windows::Win32::System::Threading::{
    AttachThreadInput, GetCurrentThreadId, OpenProcess, QueryFullProcessImageNameW,
    PROCESS_NAME_WIN32, PROCESS_QUERY_LIMITED_INFORMATION,
};
use windows::Win32::UI::Input::KeyboardAndMouse::{
    GetAsyncKeyState, GetKeyboardLayout, MapVirtualKeyExW, SendInput, ToUnicodeEx, INPUT, INPUT_0,
    INPUT_KEYBOARD, KEYBDINPUT, KEYBD_EVENT_FLAGS, KEYEVENTF_KEYUP, KEYEVENTF_UNICODE,
    MAPVK_VK_TO_VSC, VIRTUAL_KEY, VK_A, VK_BACK, VK_C, VK_CONTROL, VK_DELETE, VK_ESCAPE, VK_RETURN,
    VK_SHIFT, VK_V,
};
use windows::Win32::UI::WindowsAndMessaging::{
    AllowSetForegroundWindow, CallNextHookEx, DispatchMessageW, EnumWindows, GetForegroundWindow,
    GetMessageW, GetWindowTextW, GetWindowThreadProcessId, IsWindow, PeekMessageW,
    PostThreadMessageW, SetForegroundWindow, SetWindowsHookExW, ShowWindow, TranslateMessage,
    UnhookWindowsHookEx, HHOOK, KBDLLHOOKSTRUCT, MSG, PM_NOREMOVE, SW_RESTORE, WH_KEYBOARD_LL,
    WM_KEYDOWN, WM_KEYUP, WM_QUIT, WM_SYSKEYDOWN, WM_SYSKEYUP,
};

/// LLKHF_INJECTED — key was generated by SendInput / another process.
const LLKHF_INJECTED: u32 = 0x10;

/// How long the chat bar may sit untouched before we assume the game closed it.
/// Valorant leaves the bar open after send, so this must be longer than a
/// typical round gap — otherwise the next `sa` is typed against a "closed"
/// buffer and goes out raw. Held gameplay keys (auto-repeat) close it sooner.
const CHAT_IDLE_TIMEOUT_MS: u64 = 180_000;

/// Alt-tab / IME / overlay flicker: don't drop `chat_open` on a brief
/// non-Valorant foreground blip.
const FOCUS_OTHER_GRACE_MS: u64 = 400;

/// Foreground classification published by the poller (hook only reads this).
const FG_OTHER: u32 = 0;
const FG_VALORANT: u32 = 1;
/// IME / overlay / unreadable process — do not reset chat state.
const FG_NEUTRAL: u32 = 2;

/// After we swallow Enter-down for an expansion, suppress real Enter events
/// (especially keyup) until this many ms have elapsed. Prevents Valorant from
/// sending the unexpanded short form on the orphaned keyup.
const ENTER_SUPPRESS_MS: u64 = 900;

// --- inject pacing (Valorant is picky; too tight → empty send / dropped paste) ---
const SETTLE_AFTER_SWALLOW_MS: u64 = 100;
const CTRL_CHORD_GAP_MS: u64 = 25;
const TAP_HOLD_MS: u64 = 14;
const TAP_GAP_MS: u64 = 12;
const AFTER_CLEAR_MS: u64 = 45;
const AFTER_PASTE_MS: u64 = 90;
const AFTER_COPY_GAP_MS: u64 = 30;
const CLIP_READ_RETRIES: u32 = 6;
/// Marker planted before Ctrl+C so a failed copy is not mistaken for the
/// user's previous clipboard (which would skip `<3` and send the wrong line).
const CLIP_SENTINEL: &str = "\u{2060}vt.clip\u{2060}";
const BEFORE_SEND_ENTER_MS: u64 = 70;
const AFTER_SEND_ENTER_MS: u64 = 80;
const BACKSPACE_GAP_MS: u64 = 8;
const UNICODE_FALLBACK_GAP_MS: u64 = 18;

static STARTED: AtomicBool = AtomicBool::new(false);

/// Thread that owns the hook + its message loop (target for WM_QUIT recycle).
static HOOK_THREAD_ID: AtomicU32 = AtomicU32::new(0);
/// True while a hook thread is inside its message loop.
static HOOK_THREAD_ALIVE: AtomicBool = AtomicBool::new(false);
/// Raw `HHOOK` of the live hook, so a recycle can unhook even if the thread
/// is wedged (avoids two hooks buffering the same key as `ssaa`).
static HOOK_HANDLE: AtomicUsize = AtomicUsize::new(0);
/// Monotonic ms of the last hook callback — the liveness heartbeat.
static LAST_HOOK_MS: AtomicU64 = AtomicU64::new(0);
/// Last time we recycled the hook thread (cooldown).
static LAST_RECYCLE_MS: AtomicU64 = AtomicU64::new(0);

/// Foreground pid + kind as of the last poll. The hook only reads these
/// atomics, so it never touches a process handle.
static FG_PID: AtomicU32 = AtomicU32::new(0);
static FG_TID: AtomicU32 = AtomicU32::new(0);
static FG_KIND: AtomicU32 = AtomicU32::new(FG_OTHER);
/// Last VALORANT HWND the poller saw — overlay send focuses this window.
static LAST_VAL_HWND: AtomicUsize = AtomicUsize::new(0);
/// Foreground keyboard layout (HKL bits). Poller writes, hook reads.
static FG_HKL: AtomicUsize = AtomicUsize::new(0);
/// vk*2+shift → Unicode scalar (0 = unmapped). Rebuilt off the hook thread.
static LAYOUT_CHARS: Mutex<[u32; 512]> = Mutex::new([0; 512]);

/// When Focus::Other first became stable, for `FOCUS_OTHER_GRACE_MS`.
static OTHER_SINCE_MS: AtomicU64 = AtomicU64::new(0);

/// Monotonic clock base for the ms timestamps above.
static CLOCK: Lazy<Instant> = Lazy::new(Instant::now);

fn now_ms() -> u64 {
    CLOCK.elapsed().as_millis() as u64
}

/// One physical key that produced (or may have produced) a character.
/// `in_buffer` is false for keys `key_to_char` cannot map (TR ğüşıöç, …)
/// so backspace stays in sync with the ASCII detect buffer.
#[derive(Clone, Copy)]
struct TypedKey {
    vk: u32,
    shift: bool,
    in_buffer: bool,
}

struct ExpanderState {
    /// True while the in-game chat bar is open (Enter to open, Escape to close).
    /// Stays true after a successful send — Valorant leaves the bar open.
    chat_open: bool,
    /// Characters typed into the chat bar (best-effort ASCII for shortcut detect).
    buffer: String,
    /// Raw keys for layout-aware `ToUnicodeEx` replay off the hook thread.
    keys: Vec<TypedKey>,
    /// While we inject keys, ignore them so we don't re-buffer ourselves.
    injecting: bool,
    /// Last time we saw chat-bar activity, for `CHAT_IDLE_TIMEOUT_MS`.
    last_activity_ms: u64,
    /// Escape was pressed mid-injection — drop the pending expansion.
    abort_injection: bool,
    /// Monotonic deadline: swallow real Enter (down/up) until this ms.
    /// Set when an expansion starts so the user's Enter keyup cannot race us.
    suppress_enter_until_ms: u64,
    /// Currently held virtual keys (bit per VK 0..=255). A second down
    /// without an up is auto-repeat — movement / abilities, not chat typing.
    keys_down: [u64; 4],
}

static STATE: Mutex<ExpanderState> = Mutex::new(ExpanderState {
    chat_open: false,
    buffer: String::new(),
    keys: Vec::new(),
    injecting: false,
    last_activity_ms: 0,
    abort_injection: false,
    suppress_enter_until_ms: 0,
    keys_down: [0; 4],
});

fn key_bit(vk: u32) -> Option<(usize, u64)> {
    let i = vk as usize;
    if i >= 256 {
        return None;
    }
    Some((i / 64, 1u64 << (i % 64)))
}

fn mark_key_down(st: &mut ExpanderState, vk: u32) -> bool {
    let Some((word, bit)) = key_bit(vk) else {
        return false;
    };
    let was = st.keys_down[word] & bit != 0;
    st.keys_down[word] |= bit;
    was
}

fn mark_key_up(st: &mut ExpanderState, vk: u32) {
    if let Some((word, bit)) = key_bit(vk) {
        st.keys_down[word] &= !bit;
    }
}

fn close_chat(st: &mut ExpanderState) {
    st.chat_open = false;
    st.buffer.clear();
    st.keys.clear();
}

fn needs_expansion(raw: &str) -> bool {
    crate::chat_text::needs_chat_expansion(raw)
}

/// What currently owns keyboard focus, from the hook's point of view.
#[derive(Debug, PartialEq, Eq)]
enum Focus {
    Valorant,
    Other,
    /// Focus changed since the last poll, IME/overlay, or an unreadable
    /// process (Vanguard often blocks `OpenProcess` mid-session). Neither
    /// buffer-from-closed nor reset; the poller catches up shortly.
    Unknown,
}

/// Foreground pid via two cheap user32 calls (no process handle).
fn foreground_pid() -> u32 {
    unsafe {
        let hwnd = GetForegroundWindow();
        if hwnd.0.is_null() {
            return 0;
        }
        let mut pid: u32 = 0;
        GetWindowThreadProcessId(hwnd, Some(&mut pid));
        pid
    }
}

/// Hook-safe focus check: compares the live foreground pid against the one the
/// poller already classified. Must stay allocation- and syscall-light so the
/// callback never trips `LowLevelHooksTimeout`.
fn classify_focus(live_pid: u32, fg_pid: u32, fg_kind: u32) -> Focus {
    if live_pid == 0 {
        // Exclusive fullscreen: GetForegroundWindow is often null while
        // Valorant still has input. Trust last VALORANT; otherwise Unknown
        // so we do not close the bar the way Other would.
        return match fg_kind {
            FG_VALORANT => Focus::Valorant,
            _ => Focus::Unknown,
        };
    }
    if live_pid != fg_pid {
        return Focus::Unknown;
    }
    match fg_kind {
        FG_VALORANT => Focus::Valorant,
        FG_NEUTRAL => Focus::Unknown,
        _ => Focus::Other,
    }
}

fn focus_state() -> Focus {
    classify_focus(
        foreground_pid(),
        FG_PID.load(Ordering::Acquire),
        FG_KIND.load(Ordering::Relaxed),
    )
}

/// Re-resolve focus when the pid/tid changed, or while we are not sure it is
/// Valorant. Vanguard starts blocking `OpenProcess` mid-session; a one-shot
/// NEUTRAL classification used to stick for the rest of the process lifetime
/// because the poller only ran `classify_pid` on pid change.
fn needs_reclassify(pid: u32, tid: u32, prev_pid: u32, prev_tid: u32, prev_kind: u32) -> bool {
    pid != prev_pid || tid != prev_tid || prev_kind != FG_VALORANT
}


fn hwnd_title_is_valorant(hwnd: HWND) -> bool {
    unsafe {
        let mut buf = [0u16; 128];
        let n = GetWindowTextW(hwnd, &mut buf);
        if n <= 0 {
            return false;
        }
        let title = String::from_utf16_lossy(&buf[..n as usize]);
        title.trim().eq_ignore_ascii_case("VALORANT")
    }
}

fn classify_image_name(name: &str) -> u32 {
    if name.eq_ignore_ascii_case("VALORANT-Win64-Shipping.exe") {
        return FG_VALORANT;
    }
    let lower = name.to_ascii_lowercase();
    const NEUTRAL: &[&str] = &[
        "textinputhost.exe",
        "ctfmon.exe",
        "tabtip.exe",
        "tabtip32.exe",
        "nvidia share.exe",
        "nvidia overlay.exe",
        "nvsphelper64.exe",
        "gamebar.exe",
        "gamebarftw.exe",
        "riotclientservices.exe",
        "riotclientux.exe",
        "applicationframehost.exe",
    ];
    if NEUTRAL.iter().any(|n| lower == *n) || lower.contains("ime") {
        FG_NEUTRAL
    } else {
        FG_OTHER
    }
}

/// Resolve a pid's image name — the expensive part, kept off the hook thread.
fn classify_pid(pid: u32, hwnd: HWND) -> u32 {
    if hwnd_title_is_valorant(hwnd) {
        return FG_VALORANT;
    }
    unsafe {
        let Ok(proc) = OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, false, pid) else {
            // Vanguard often starts blocking process queries mid-session.
            // Don't treat that as "user left the game".
            return FG_NEUTRAL;
        };
        let mut buf = [0u16; 512];
        let mut size = buf.len() as u32;
        let ok = QueryFullProcessImageNameW(
            proc,
            PROCESS_NAME_WIN32,
            PWSTR(buf.as_mut_ptr()),
            &mut size,
        )
        .is_ok();
        let _ = windows::Win32::Foundation::CloseHandle(proc);
        if !ok {
            return FG_NEUTRAL;
        }
        let path = String::from_utf16_lossy(&buf[..size as usize]);
        let name = path.rsplit(['\\', '/']).next().unwrap_or(path.as_str());
        classify_image_name(name)
    }
}

/// Keep `FG_PID` / `FG_KIND` current so the hook can stay cheap.
fn start_foreground_poller() {
    std::thread::Builder::new()
        .name("chat-expander-fg".into())
        .spawn(|| loop {
            unsafe {
                let hwnd = GetForegroundWindow();
                if hwnd.0.is_null() {
                    // Exclusive-fullscreen flicker — keep the last classification.
                    std::thread::sleep(Duration::from_millis(80));
                    continue;
                }
                let mut pid: u32 = 0;
                let tid = GetWindowThreadProcessId(hwnd, Some(&mut pid));
                if pid != 0 {
                    refresh_layout_map(GetKeyboardLayout(tid));
                    let prev_pid = FG_PID.load(Ordering::Relaxed);
                    let prev_tid = FG_TID.load(Ordering::Relaxed);
                    let prev_kind = FG_KIND.load(Ordering::Relaxed);
                    if needs_reclassify(pid, tid, prev_pid, prev_tid, prev_kind) {
                        let kind = classify_pid(pid, hwnd);
                        // Publish the classification before the pid it belongs to.
                        FG_KIND.store(kind, Ordering::Relaxed);
                        FG_TID.store(tid, Ordering::Relaxed);
                        FG_PID.store(pid, Ordering::Release);
                        if kind == FG_VALORANT && !hwnd.0.is_null() {
                            LAST_VAL_HWND.store(hwnd.0 as usize, Ordering::Relaxed);
                        }
                        if kind != prev_kind || pid != prev_pid {
                            tracing::debug!(
                                "[ChatExpander] Focus pid {} → {} kind {} → {}",
                                prev_pid,
                                pid,
                                prev_kind,
                                kind
                            );
                        }
                    }
                }

            }
            // Faster than the old 150 ms — reduces Focus::Unknown windows that
            // used to drop short shortcuts like `sa` mid-type.
            std::thread::sleep(Duration::from_millis(80));
        })
        .ok();
}

fn shift_down() -> bool {
    unsafe { GetAsyncKeyState(VK_SHIFT.0 as i32) as u16 & 0x8000 != 0 }
}

fn ctrl_down() -> bool {
    unsafe { GetAsyncKeyState(VK_CONTROL.0 as i32) as u16 & 0x8000 != 0 }
}

/// Map a virtual-key to a typed character without `ToUnicode` / `GetKeyboardState`.
/// Those APIs are layout-aware but routinely stall a `WH_KEYBOARD_LL` callback
/// past `LowLevelHooksTimeout` (especially with TR-Q / IME), after which Windows
/// silently unhooks us.
///
/// The foreground poller precomputes a vk+shift table with `ToUnicodeEx` so
/// TR-Q Shift+period is `:` (not US `>`). Falling back to US-QWERTY used to
/// turn `:D` into `>D`, which the expander then treated as an enemy agent tag
/// and pasted the mangled buffer. The real line (Turkish letters included) is
/// still read from the chat box via clipboard right before expansion.
fn key_to_char(vk: u32) -> Option<char> {
    let shift = shift_down();
    if FG_HKL.load(Ordering::Relaxed) != 0 {
        layout_char(vk, shift)
    } else {
        key_to_char_us(vk, shift)
    }
}

fn layout_char(vk: u32, shift: bool) -> Option<char> {
    if vk > 255 {
        return None;
    }
    let n = LAYOUT_CHARS.lock()[(vk as usize) * 2 + shift as usize];
    char::from_u32(n).filter(|c| *c != '\0')
}

/// US-QWERTY fallback used only before the first layout snapshot.
fn key_to_char_us(vk: u32, shift: bool) -> Option<char> {
    match vk {
        // 0-9
        0x30..=0x39 => {
            let digits = b"0123456789";
            let shifted = b")!@#$%^&*(";
            let i = (vk - 0x30) as usize;
            Some(if shift {
                shifted[i] as char
            } else {
                digits[i] as char
            })
        }
        // A-Z
        0x41..=0x5A => {
            let base = (b'a' + (vk - 0x41) as u8) as char;
            Some(if shift {
                base.to_ascii_uppercase()
            } else {
                base
            })
        }
        // Space
        0x20 => Some(' '),
        // OEM keys common for `<` `>` `/` etc. (US + some TR layouts)
        0xBC => Some(if shift { '<' } else { ',' }), // VK_OEM_COMMA
        0xBE => Some(if shift { '>' } else { '.' }), // VK_OEM_PERIOD
        0xBF => Some(if shift { '?' } else { '/' }), // VK_OEM_2
        0xBA => Some(if shift { ':' } else { ';' }), // VK_OEM_1
        // VK_OEM_102 — key between LShift and Z on many EU/TR boards (`<` `>`)
        0xE2 => Some(if shift { '>' } else { '<' }),
        // `!` still typeable (no longer a translate prefix)
        // already covered by shift+1 → '!'
        _ => None,
    }
}

/// Rebuild the hook's vk→char table for `hkl`. Cheap no-op when layout unchanged.
fn refresh_layout_map(hkl: windows::Win32::UI::Input::KeyboardAndMouse::HKL) {
    let raw = hkl.0 as usize;
    if raw == 0 || FG_HKL.load(Ordering::Relaxed) == raw {
        return;
    }
    let mut cells = [0u32; 512];
    unsafe {
        let mut state = [0u8; 256];
        let mut buf = [0u16; 16];
        for vk in 0u32..=255 {
            if !is_typeable_vk(vk) {
                continue;
            }
            let scan = MapVirtualKeyExW(vk, MAPVK_VK_TO_VSC, hkl);
            for shift in [false, true] {
                state.fill(0);
                if shift {
                    state[VK_SHIFT.0 as usize] = 0x80;
                }
                let n = ToUnicodeEx(vk, scan, &state, &mut buf, 0, hkl);
                if n > 0 {
                    let n = (n as usize).min(buf.len());
                    if let Some(ch) = char::decode_utf16(buf[..n].iter().copied()).next() {
                        if let Ok(ch) = ch {
                            cells[(vk as usize) * 2 + shift as usize] = ch as u32;
                        }
                    }
                }
            }
        }
    }
    *LAYOUT_CHARS.lock() = cells;
    FG_HKL.store(raw, Ordering::Relaxed);
}


fn send_vk(vk: VIRTUAL_KEY, down: bool) {
    unsafe {
        let flags = if down {
            KEYBD_EVENT_FLAGS(0)
        } else {
            KEYEVENTF_KEYUP
        };
        let input = INPUT {
            r#type: INPUT_KEYBOARD,
            Anonymous: INPUT_0 {
                ki: KEYBDINPUT {
                    wVk: vk,
                    wScan: 0,
                    dwFlags: flags,
                    time: 0,
                    dwExtraInfo: 0,
                },
            },
        };
        let _ = SendInput(&[input], std::mem::size_of::<INPUT>() as i32);
    }
}

fn send_unicode_char(ch: char) {
    // BMP only (our expansions stay in BMP).
    let unit = ch as u16;
    unsafe {
        let down = INPUT {
            r#type: INPUT_KEYBOARD,
            Anonymous: INPUT_0 {
                ki: KEYBDINPUT {
                    wVk: VIRTUAL_KEY(0),
                    wScan: unit,
                    dwFlags: KEYEVENTF_UNICODE,
                    time: 0,
                    dwExtraInfo: 0,
                },
            },
        };
        let up = INPUT {
            r#type: INPUT_KEYBOARD,
            Anonymous: INPUT_0 {
                ki: KEYBDINPUT {
                    wVk: VIRTUAL_KEY(0),
                    wScan: unit,
                    dwFlags: KEYEVENTF_UNICODE | KEYEVENTF_KEYUP,
                    time: 0,
                    dwExtraInfo: 0,
                },
            },
        };
        let _ = SendInput(&[down, up], std::mem::size_of::<INPUT>() as i32);
    }
}

fn send_unicode_string_slow(s: &str) {
    // Fallback only — Valorant often drops mid-string when fed too fast.
    for ch in s.chars() {
        send_unicode_char(ch);
        std::thread::sleep(Duration::from_millis(UNICODE_FALLBACK_GAP_MS));
    }
}

fn tap_key(vk: VIRTUAL_KEY) {
    send_vk(vk, true);
    std::thread::sleep(Duration::from_millis(TAP_HOLD_MS));
    send_vk(vk, false);
    std::thread::sleep(Duration::from_millis(TAP_GAP_MS));
}

/// Put Unicode text on the Windows clipboard (CF_UNICODETEXT).
///
/// `OpenClipboard` fails whenever another process holds it — clipboard managers
/// do this constantly — so retry briefly instead of falling straight back to
/// the slow SendInput path that Valorant tends to cut mid-string.
fn set_clipboard_text(text: &str) -> bool {
    unsafe {
        let mut opened = false;
        for attempt in 0..6 {
            if OpenClipboard(HWND::default()).is_ok() {
                opened = true;
                break;
            }
            if attempt < 5 {
                std::thread::sleep(Duration::from_millis(20));
            }
        }
        if !opened {
            tracing::warn!("[ChatExpander] OpenClipboard busy after retries");
            return false;
        }
        let _ = EmptyClipboard();
        let wide: Vec<u16> = text.encode_utf16().chain(std::iter::once(0)).collect();
        let bytes = wide.len() * std::mem::size_of::<u16>();
        let Ok(hmem) = GlobalAlloc(GMEM_MOVEABLE, bytes) else {
            let _ = CloseClipboard();
            return false;
        };
        let ptr = GlobalLock(hmem);
        if ptr.is_null() {
            let _ = CloseClipboard();
            return false;
        }
        std::ptr::copy_nonoverlapping(wide.as_ptr(), ptr as *mut u16, wide.len());
        let _ = GlobalUnlock(hmem);
        // Ownership of hmem transfers to the clipboard on success.
        if SetClipboardData(CF_UNICODETEXT, HANDLE(hmem.0 as _)).is_err() {
            let _ = CloseClipboard();
            return false;
        }
        let _ = CloseClipboard();
        true
    }
}

/// Read `CF_UNICODETEXT` from the clipboard. Returns `None` if another process
/// holds it, or if the clip is not Unicode text.
fn get_clipboard_text() -> Option<String> {
    unsafe {
        let mut opened = false;
        for attempt in 0..6 {
            if OpenClipboard(HWND::default()).is_ok() {
                opened = true;
                break;
            }
            if attempt < 5 {
                std::thread::sleep(Duration::from_millis(20));
            }
        }
        if !opened {
            return None;
        }
        let handle = match GetClipboardData(CF_UNICODETEXT) {
            Ok(h) => h,
            Err(_) => {
                let _ = CloseClipboard();
                return None;
            }
        };
        if handle.0.is_null() {
            let _ = CloseClipboard();
            return None;
        }
        let hmem = HGLOBAL(handle.0);
        let ptr = GlobalLock(hmem);
        if ptr.is_null() {
            let _ = CloseClipboard();
            return None;
        }
        let p = ptr as *const u16;
        let mut len = 0usize;
        // Hard cap so a huge clip cannot stall the inject thread.
        while len < 4096 && *p.add(len) != 0 {
            len += 1;
        }
        let text = String::from_utf16_lossy(std::slice::from_raw_parts(p, len));
        let _ = GlobalUnlock(hmem);
        let _ = CloseClipboard();
        Some(text)
    }
}

/// Select-all + copy the in-game chat input, then read it back.
///
/// The hook buffer only sees US-ASCII (`key_to_char` cannot call `ToUnicode`).
/// Valorant already has the correctly typed line — including ğüşıöç — so we
/// steal that instead of reconstructing from virtual keys.
fn copy_chat_line() -> Option<String> {
    // Plant a marker so we can tell "copy never happened" from "old clip".
    let _ = set_clipboard_text(CLIP_SENTINEL);

    send_vk(VK_CONTROL, true);
    std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));
    tap_key(VK_A);
    std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));
    tap_key(VK_C);
    std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));
    send_vk(VK_CONTROL, false);

    for _ in 0..CLIP_READ_RETRIES {
        std::thread::sleep(Duration::from_millis(AFTER_COPY_GAP_MS));
        if let Some(s) = get_clipboard_text() {
            if s != CLIP_SENTINEL && !s.is_empty() {
                return Some(s);
            }
        }
    }
    None
}

/// Keys that can produce a character (letters, digits, space, OEM).
fn is_typeable_vk(vk: u32) -> bool {
    matches!(
        vk,
        0x20 | 0x30..=0x39 | 0x41..=0x5A | 0xBA..=0xC0 | 0xDB..=0xDF | 0xE2
    )
}

/// Replay recorded virtual keys with the foreground layout. Safe off the hook
/// thread — `ToUnicodeEx` is what we cannot call inside `WH_KEYBOARD_LL`.
fn decode_typed_keys(keys: &[TypedKey]) -> String {
    if keys.is_empty() {
        return String::new();
    }
    unsafe {
        let tid = FG_TID.load(Ordering::Relaxed);
        let hkl = GetKeyboardLayout(tid);
        let mut out = String::with_capacity(keys.len());
        let mut state = [0u8; 256];
        let mut buf = [0u16; 16];
        for k in keys {
            state.fill(0);
            if k.shift {
                state[VK_SHIFT.0 as usize] = 0x80;
            }
            let scan = MapVirtualKeyExW(k.vk, MAPVK_VK_TO_VSC, hkl);
            let n = ToUnicodeEx(k.vk, scan, &state, &mut buf, 0, hkl);
            if n > 0 {
                let n = (n as usize).min(buf.len());
                out.extend(
                    char::decode_utf16(buf[..n].iter().copied()).map(|r| r.unwrap_or('\u{FFFD}')),
                );
            }
        }
        out
    }
}

/// Prefer the real in-game line (clipboard or layout-decoded keys) over the
/// ASCII hook buffer. A candidate must still look like a shortcut so a stale
/// clipboard cannot swallow `<3`. Longer wins — Turkish letters make the
/// real line longer than the mangled buffer. Same length: clipboard, then
/// decoded keys, then the hook buffer — so a copied `:D` beats US-mapped `>D`.
fn pick_expand_source(buffer: &str, copied: Option<&str>, decoded: Option<&str>) -> String {
    fn clean(s: &str) -> Option<String> {
        let c = s.trim_end_matches(['\r', '\n']);
        if c.is_empty() || c.chars().count() > 500 {
            None
        } else {
            Some(c.to_string())
        }
    }

    // 0 = clipboard, 1 = decoded keys, 2 = ASCII buffer.
    let mut cands: Vec<(u8, String)> = Vec::with_capacity(3);
    if let Some(c) = copied.and_then(clean) {
        cands.push((0, c));
    }
    if let Some(c) = decoded.and_then(clean) {
        cands.push((1, c));
    }
    cands.push((2, buffer.to_string()));

    cands.sort_by(|a, b| {
        let ae = crate::chat_text::needs_chat_expansion(&a.1);
        let be = crate::chat_text::needs_chat_expansion(&b.1);
        be.cmp(&ae)
            .then_with(|| b.1.chars().count().cmp(&a.1.chars().count()))
            .then_with(|| a.0.cmp(&b.0))
    });
    cands.into_iter().next().map(|(_, s)| s).unwrap_or_default()
}


/// Clear whatever is currently in the chat input line.
fn clear_chat_line(original: &str) {
    // Select-all + delete
    send_vk(VK_CONTROL, true);
    std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));
    tap_key(VK_A);
    std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));
    send_vk(VK_CONTROL, false);
    std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));
    tap_key(VK_DELETE);
    std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));

    // Backspace original length (+2) if select-all failed (caret still on short form).
    let n = original.chars().count().saturating_add(2).min(64);
    for _ in 0..n {
        send_vk(VK_BACK, true);
        std::thread::sleep(Duration::from_millis(TAP_HOLD_MS / 2));
        send_vk(VK_BACK, false);
        std::thread::sleep(Duration::from_millis(BACKSPACE_GAP_MS));
    }
    std::thread::sleep(Duration::from_millis(AFTER_CLEAR_MS));
}

fn paste_clipboard() {
    send_vk(VK_CONTROL, true);
    std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));
    tap_key(VK_V);
    std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));
    send_vk(VK_CONTROL, false);
    // Give Valorant's chat widget time to accept the paste before we hit Enter.
    std::thread::sleep(Duration::from_millis(AFTER_PASTE_MS));
}

/// Extra settle after paste for longer expansions (agent tags, …).
fn paste_settle_extra(text: &str) -> u64 {
    let n = text.chars().count() as u64;
    if n > 40 {
        40
    } else if n > 20 {
        20
    } else {
        0
    }
}

/// Clears `injecting` if the inject thread panics, so Enter is never swallowed
/// for the rest of the session.
struct InjectingGuard;
impl Drop for InjectingGuard {
    fn drop(&mut self) {
        let mut st = STATE.lock();
        if st.injecting {
            st.injecting = false;
            st.abort_injection = false;
        }
    }
}

/// Put the user's previous clipboard back after we steal it for copy/paste.
struct ClipboardRestore(Option<String>);
impl Drop for ClipboardRestore {
    fn drop(&mut self) {
        if let Some(prev) = self.0.take() {
            if prev != CLIP_SENTINEL {
                let _ = set_clipboard_text(&prev);
            }
        }
    }
}

/// Expand shortcuts then inject into the game chat box.
/// Always runs off the hook thread — never block the keyboard hook.
fn inject_expanded_from_raw(raw: String) {
    std::thread::spawn(move || {
        // Claim the injection slot *before* transforming: expansion can take a beat
        // network for seconds and anything typed meanwhile must not land in the
        // buffer we are about to replace.
        let keys = {
            let mut st = STATE.lock();
            st.injecting = true;
            st.abort_injection = false;
            let keys = std::mem::take(&mut st.keys);
            st.buffer.clear();
            // Cover the user's Enter keyup + our whole inject sequence.
            st.suppress_enter_until_ms = now_ms().saturating_add(ENTER_SUPPRESS_MS);
            keys
        };
        let _guard = InjectingGuard;

        // Escape during a slow transform means the user left the chat bar —
        // typing now would feed the expansion to the game as keybinds.
        {
            let mut st = STATE.lock();
            if st.abort_injection {
                st.injecting = false;
                st.abort_injection = false;
                st.buffer.clear();
                st.suppress_enter_until_ms = 0;
                tracing::info!("[ChatExpander] Expansion aborted (Escape)");
                return;
            }
        }

        // Let the swallowed Enter (and any orphaned keyup suppress) settle.
        std::thread::sleep(Duration::from_millis(SETTLE_AFTER_SWALLOW_MS));

        if STATE.lock().abort_injection {
            let mut st = STATE.lock();
            st.injecting = false;
            st.abort_injection = false;
            st.buffer.clear();
            st.suppress_enter_until_ms = 0;
            tracing::info!("[ChatExpander] Expansion aborted before inject");
            return;
        }

        // Read the real typed line from the chat box. The hook buffer is
        // ASCII-only (no ToUnicode), so "günaydın <3" arrives as "gnaydn <3"
        // and would wipe the Turkish letters on paste.
        let _clip_restore = ClipboardRestore(get_clipboard_text());
        let copied = copy_chat_line();
        let decoded = decode_typed_keys(&keys);
        let decoded = if decoded.is_empty() {
            None
        } else {
            Some(decoded)
        };
        let source = pick_expand_source(&raw, copied.as_deref(), decoded.as_deref());
        if source != raw {
            tracing::debug!(
                "[ChatExpander] Using in-game line ({} chars) over hook buffer ({} chars)",
                source.chars().count(),
                raw.chars().count()
            );
        }

        let text = crate::chat_text::transform_outgoing_chat(&source);

        // Expansion may have taken a moment — re-check Escape and extend
        // the Enter suppress so it still covers clear/paste/send.
        {
            let mut st = STATE.lock();
            if st.abort_injection {
                st.injecting = false;
                st.abort_injection = false;
                st.buffer.clear();
                st.suppress_enter_until_ms = 0;
                tracing::info!("[ChatExpander] Expansion aborted (Escape)");
                return;
            }
            st.suppress_enter_until_ms = now_ms().saturating_add(ENTER_SUPPRESS_MS);
        }

        // Wipe short form (`sa`, `<3`, …) so we never get `saSelamun…`.
        clear_chat_line(&source);

        // Prefer clipboard paste — full string at once, no mid-cut "Selamun A".
        // Retry once: clipboard managers often hold the clip on first OpenClipboard.
        let mut pasted = false;
        for attempt in 0..2 {
            if set_clipboard_text(&text) {
                paste_clipboard();
                pasted = true;
                break;
            }
            if attempt == 0 {
                tracing::debug!("[ChatExpander] Clipboard busy, retrying once");
                std::thread::sleep(Duration::from_millis(40));
            }
        }

        if !pasted {
            tracing::warn!("[ChatExpander] Clipboard paste failed; slow Unicode fallback");
            send_unicode_string_slow(&text);
            std::thread::sleep(Duration::from_millis(AFTER_PASTE_MS));
        } else {
            let extra = paste_settle_extra(&text);
            if extra > 0 {
                std::thread::sleep(Duration::from_millis(extra));
            }
        }

        if STATE.lock().abort_injection {
            let mut st = STATE.lock();
            st.injecting = false;
            st.abort_injection = false;
            st.buffer.clear();
            st.suppress_enter_until_ms = 0;
            tracing::info!("[ChatExpander] Expansion aborted before send");
            return;
        }

        // Send the expanded line.
        std::thread::sleep(Duration::from_millis(BEFORE_SEND_ENTER_MS));
        tap_key(VK_RETURN);

        // Keep chat_open — Valorant leaves the bar open after send.
        std::thread::sleep(Duration::from_millis(AFTER_SEND_ENTER_MS));
        let mut st = STATE.lock();
        st.injecting = false;
        st.abort_injection = false;
        st.chat_open = true;
        st.buffer.clear();
        st.last_activity_ms = now_ms();
        // Brief tail suppress so our synthetic Enter's pair can't double-send
        // if the user still holds the physical key.
        st.suppress_enter_until_ms = now_ms().saturating_add(200);
        drop(st);

        tracing::info!(
            "[ChatExpander] Injected {:?} → {:?} (paste={}, src_chars={})",
            source.trim(),
            text,
            pasted,
            source.chars().count()
        );
    });
}

unsafe extern "system" fn keyboard_proc(code: i32, wparam: WPARAM, lparam: LPARAM) -> LRESULT {
    if code < 0 {
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    // Heartbeat first: any callback proves Windows has not dropped us.
    LAST_HOOK_MS.store(now_ms(), Ordering::Relaxed);

    let kb = &*(lparam.0 as *const KBDLLHOOKSTRUCT);
    let vk = kb.vkCode;

    if !crate::chat_text::shortcuts_enabled() {
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    let msg = wparam.0 as u32;
    let is_down = msg == WM_KEYDOWN || msg == WM_SYSKEYDOWN;
    let is_up = msg == WM_KEYUP || msg == WM_SYSKEYUP;
    if !is_down && !is_up {
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    // Ignore synthetic keys (our SendInput + any other injectors).
    let flags = kb.flags.0;
    if flags & LLKHF_INJECTED != 0 {
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    {
        let mut st = STATE.lock();
        if is_up {
            mark_key_up(&mut st, vk);
        } else if mark_key_down(&mut st, vk) {
            // Auto-repeat: the user is holding a key (WASD / jump / abilities).
            // Chat typing does not hold letters, so the bar cannot still be open.
            // Backspace-hold (delete), Enter-hold (open/send) and modifiers are
            // the exceptions — those happen while the bar is genuinely open.
            let allow_repeat = vk == VK_BACK.0 as u32
                || vk == VK_RETURN.0 as u32
                || vk == VK_ESCAPE.0 as u32
                || vk == VK_SHIFT.0 as u32
                || vk == VK_CONTROL.0 as u32;
            if !allow_repeat && st.chat_open {
                close_chat(&mut st);
                tracing::debug!("[ChatExpander] Held key — chat assumed closed");
            }
        }

        if st.injecting {
            // Mid-injection only Escape matters: the user bailed out of the
            // chat bar, so cancel the pending expansion.
            if is_down && vk == VK_ESCAPE.0 as u32 {
                st.abort_injection = true;
                close_chat(&mut st);
            }
            // Swallow physical Enter while we own the send sequence so a held
            // key cannot double-fire alongside our synthetic Enter.
            if vk == VK_RETURN.0 as u32 {
                return LRESULT(1);
            }
            return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
        }

        // Orphan Enter keyup (or a held Enter) after we swallowed the down edge
        // for expansion — must not reach Valorant or it may send `sa` raw.
        if vk == VK_RETURN.0 as u32 && now_ms() < st.suppress_enter_until_ms {
            return LRESULT(1);
        }
    }

    // Only key-downs shape the buffer; skipping key-ups halves the work the
    // hook does per keystroke, which is what keeps us under the hook timeout.
    if !is_down {
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    // Focus::Unknown used to hard-drop keys (poller lag) — fatal for 2-letter
    // shortcuts like `sa`. Keep going: Enter must be able to re-open the bar
    // after a match, even while the poller/HWND has not caught up.
    match focus_state() {
        Focus::Valorant => {
            OTHER_SINCE_MS.store(0, Ordering::Relaxed);
        }
        Focus::Other => {
            let now = now_ms();
            let since = OTHER_SINCE_MS.load(Ordering::Relaxed);
            if since == 0 {
                OTHER_SINCE_MS.store(now, Ordering::Relaxed);
            } else if now.saturating_sub(since) >= FOCUS_OTHER_GRACE_MS {
                let mut st = STATE.lock();
                if st.chat_open || !st.buffer.is_empty() {
                    close_chat(&mut st);
                }
                return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
            }
            // Brief flicker (IME/overlay): keep buffering if chat was open.
            if !STATE.lock().chat_open {
                return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
            }
        }
        Focus::Unknown => {
            OTHER_SINCE_MS.store(0, Ordering::Relaxed);
        }
    }

    // A mouse click, an alternate chat bind or Valorant's own auto-hide can
    // close the bar without us ever seeing Escape. Time the state out so the
    // next Enter is read as "open" rather than swallowed as a send.
    {
        let mut st = STATE.lock();
        if st.chat_open && now_ms().saturating_sub(st.last_activity_ms) > CHAT_IDLE_TIMEOUT_MS {
            close_chat(&mut st);
            tracing::debug!("[ChatExpander] Chat idle timeout — assuming closed");
        }
    }

    // Ignore pure modifiers.
    if vk == VK_SHIFT.0 as u32 || vk == VK_CONTROL.0 as u32 {
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    // Escape closes chat.
    if vk == VK_ESCAPE.0 as u32 {
        let mut st = STATE.lock();
        close_chat(&mut st);
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    // Enter: open / send / expand.
    if vk == VK_RETURN.0 as u32 {
        let mut st = STATE.lock();
        st.last_activity_ms = now_ms();

        if !st.chat_open {
            // Opening the chat bar (first Enter).
            st.chat_open = true;
            st.buffer.clear();
            st.keys.clear();
            tracing::debug!("[ChatExpander] Chat opened");
            return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
        }

        // Chat already open → this Enter is a send (or empty close).
        let raw = st.buffer.clone();
        let empty = raw.trim().is_empty() && st.keys.is_empty();
        drop(st);

        if empty {
            // Empty Enter usually closes chat in Valorant.
            let mut st = STATE.lock();
            close_chat(&mut st);
            tracing::debug!("[ChatExpander] Empty enter — chat closed");
            return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
        }

        if needs_expansion(&raw) {
            tracing::info!("[ChatExpander] Expanding: {:?}", raw.trim());
            // Swallow Enter down; suppress matching up + inject expanded text.
            // chat_open stays true after inject.
            {
                let mut st = STATE.lock();
                st.suppress_enter_until_ms = now_ms().saturating_add(ENTER_SUPPRESS_MS);
            }
            inject_expanded_from_raw(raw);
            return LRESULT(1);
        }

        // Normal message: let Enter through, keep chat open for the next line.
        let mut st = STATE.lock();
        st.buffer.clear();
        st.keys.clear();
        st.chat_open = true;
        tracing::debug!("[ChatExpander] Normal send, chat stays open");
        return CallNextHookEx(HHOOK::default(), code, wparam, lparam);
    }

    // Buffer while chat is open.
    {
        let mut st = STATE.lock();
        if st.chat_open {
            st.last_activity_ms = now_ms();
            if vk == VK_BACK.0 as u32 {
                if let Some(k) = st.keys.pop() {
                    if k.in_buffer {
                        st.buffer.pop();
                    }
                }
            } else if !ctrl_down() && is_typeable_vk(vk) && st.keys.len() < 500 {
                let ch = key_to_char(vk);
                if let Some(ch) = ch {
                    st.buffer.push(ch);
                }
                st.keys.push(TypedKey {
                    vk,
                    shift: shift_down(),
                    in_buffer: ch.is_some(),
                });
            }
        }
    }

    CallNextHookEx(HHOOK::default(), code, wparam, lparam)
}

/// Install the low-level hook. Must run on the thread that pumps messages.
unsafe fn install_hook() -> Option<HHOOK> {
    match SetWindowsHookExW(WH_KEYBOARD_LL, Some(keyboard_proc), HINSTANCE::default(), 0) {
        Ok(h) => Some(h),
        Err(e) => {
            tracing::error!("[ChatExpander] SetWindowsHookEx failed: {}", e);
            None
        }
    }
}

/// Run the hook + message loop on this thread until `WM_QUIT`.
unsafe fn hook_thread_main(first: bool) {
    let tid = GetCurrentThreadId();
    HOOK_THREAD_ID.store(tid, Ordering::Relaxed);
    HOOK_THREAD_ALIVE.store(true, Ordering::Relaxed);

    // A thread only gets a message queue after the first peek/get.
    // SetWindowsHookEx(WH_KEYBOARD_LL) is unreliable without one.
    let mut msg = MSG::default();
    let _ = PeekMessageW(&mut msg, HWND::default(), 0, 0, PM_NOREMOVE);

    let hook = install_hook();
    if let Some(h) = hook {
        HOOK_HANDLE.store(h.0 as usize, Ordering::SeqCst);
        LAST_HOOK_MS.store(now_ms(), Ordering::Relaxed);
        if first {
            tracing::info!("[ChatExpander] In-game sa/as/<3 expander active");
        } else {
            tracing::info!("[ChatExpander] Keyboard hook thread recycled");
        }
    } else {
        HOOK_HANDLE.store(0, Ordering::SeqCst);
        tracing::error!("[ChatExpander] Hook install failed; watchdog will retry");
    }

    loop {
        let res = GetMessageW(&mut msg, HWND::default(), 0, 0).0;
        if res == -1 {
            std::thread::sleep(Duration::from_millis(50));
            continue;
        }
        if res == 0 || msg.message == WM_QUIT {
            break;
        }
        let _ = TranslateMessage(&msg);
        DispatchMessageW(&msg);
    }

    HOOK_HANDLE.store(0, Ordering::SeqCst);
    if let Some(h) = hook {
        let _ = UnhookWindowsHookEx(h);
    }
    if HOOK_THREAD_ID.load(Ordering::Relaxed) == tid {
        HOOK_THREAD_ID.store(0, Ordering::Relaxed);
    }
    HOOK_THREAD_ALIVE.store(false, Ordering::Relaxed);
}

fn spawn_hook_thread(first: bool) {
    std::thread::Builder::new()
        .name("chat-expander".into())
        .spawn(move || unsafe {
            hook_thread_main(first);
        })
        .ok();
}

/// Tear down the current hook thread and start a fresh one.
/// Same-thread `SetWindowsHookEx` after a silent unhook often never fires again.
fn recycle_hook_thread(reason: &str) {
    let now = now_ms();
    if now.saturating_sub(LAST_RECYCLE_MS.load(Ordering::Relaxed)) < 1_500 {
        return;
    }
    LAST_RECYCLE_MS.store(now, Ordering::Relaxed);
    tracing::warn!("[ChatExpander] Recreating keyboard hook thread ({reason})");

    let raw = HOOK_HANDLE.swap(0, Ordering::SeqCst);
    if raw != 0 {
        unsafe {
            let _ = UnhookWindowsHookEx(HHOOK(raw as *mut _));
        }
    }
    let tid = HOOK_THREAD_ID.swap(0, Ordering::Relaxed);
    if tid != 0 {
        unsafe {
            let _ = PostThreadMessageW(tid, WM_QUIT, WPARAM(0), LPARAM(0));
        }
        for _ in 0..40 {
            if !HOOK_THREAD_ALIVE.load(Ordering::Relaxed) {
                break;
            }
            std::thread::sleep(Duration::from_millis(10));
        }
    }

    {
        let mut st = STATE.lock();
        if !st.injecting {
            close_chat(&mut st);
        }
    }

    spawn_hook_thread(false);
}

/// Virtual keys sampled by the watchdog. A transition here with no matching
/// hook heartbeat means Windows dropped us.
const WATCH_VKS: &[i32] = &[
    0x0D, // VK_RETURN
    0x1B, // VK_ESCAPE
    0x20, // VK_SPACE
    0x08, // VK_BACK
    0x10, // VK_SHIFT
    0x11, // VK_CONTROL
    // 0-9
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39,
    // A-Z
    0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4A, 0x4B, 0x4C, 0x4D, 0x4E, 0x4F,
    0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5A,
    // Common OEM (`<` `>` `/` `;` on US + TR-Q OEM_102)
    0xBA, 0xBC, 0xBE, 0xBF, 0xE2,
];

fn sample_watch_keys(prev: &mut [u64; 4]) -> bool {
    let mut changed = false;
    unsafe {
        for &vk in WATCH_VKS {
            let down = GetAsyncKeyState(vk) as u16 & 0x8000 != 0;
            let Some((word, bit)) = key_bit(vk as u32) else {
                continue;
            };
            let was = prev[word] & bit != 0;
            if down != was {
                changed = true;
                if down {
                    prev[word] |= bit;
                } else {
                    prev[word] &= !bit;
                }
            }
        }
    }
    changed
}

/// Detect and recover from Windows silently unhooking us.
///
/// Uses physical key transitions instead of a SendInput probe: Vanguard often
/// starts blocking synthetic keys mid-session, which made the old probe look
/// dead and reset chat state every few seconds even when the hook was fine.
fn start_hook_watchdog() {
    std::thread::Builder::new()
        .name("chat-expander-watchdog".into())
        .spawn(|| {
            let mut prev = [0u64; 4];
            let _ = sample_watch_keys(&mut prev);
            let mut misses: u8 = 0;

            loop {
                std::thread::sleep(Duration::from_millis(120));

                if !crate::chat_text::shortcuts_enabled() {
                    misses = 0;
                    continue;
                }
                if STATE.lock().injecting {
                    misses = 0;
                    continue;
                }

                // Thread vanished (panic / WM_QUIT we didn't request).
                // Give the first spawn a moment — watchdog starts next to it.
                if !HOOK_THREAD_ALIVE.load(Ordering::Relaxed) {
                    if now_ms() < 3_000 && LAST_RECYCLE_MS.load(Ordering::Relaxed) == 0 {
                        continue;
                    }
                    recycle_hook_thread("hook thread exited");
                    let _ = sample_watch_keys(&mut prev);
                    misses = 0;
                    continue;
                }

                if !sample_watch_keys(&mut prev) {
                    continue;
                }

                // A physical key changed. If the hook is alive it already
                // stamped LAST_HOOK_MS (LL callbacks run before the key is
                // visible to GetAsyncKeyState in other threads).
                if now_ms().saturating_sub(LAST_HOOK_MS.load(Ordering::Relaxed)) > 400 {
                    misses = misses.saturating_add(1);
                    if misses >= 3 {
                        recycle_hook_thread("no hook heartbeat on physical keys");
                        let _ = sample_watch_keys(&mut prev);
                        misses = 0;
                    }
                } else {
                    misses = 0;
                }
            }
        })
        .ok();
}

/// Start the low-level keyboard hook on a dedicated message-loop thread,
/// plus the foreground poller and the hook watchdog.
pub fn start() {
    if STARTED.swap(true, Ordering::SeqCst) {
        return;
    }

    Lazy::force(&CLOCK);
    LAST_HOOK_MS.store(now_ms(), Ordering::Relaxed);
    start_foreground_poller();
    spawn_hook_thread(true);
    start_hook_watchdog();
}

/// Clear buffered chat state when the feature is toggled off. The hook itself
/// stays installed and gates on `chat_text::shortcuts_enabled()`, so the
/// watchdog keeps it healthy for when the user turns shortcuts back on.
pub fn on_enabled_changed(on: bool) {
    let mut st = STATE.lock();
    close_chat(&mut st);
    st.suppress_enter_until_ms = 0;
    st.keys_down = [0; 4];
    if !on && st.injecting {
        st.abort_injection = true;
    }
}

/// Valorant tears down the chat widget on phase changes (match end, agent
/// select, menus). Stale `chat_open` makes the next Enter look like a send,
/// and with Focus::Unknown the expander never re-armed until restart.
pub fn on_match_phase(phase: &str) {
    let mut st = STATE.lock();
    if st.injecting {
        return;
    }
    if st.chat_open || !st.buffer.is_empty() {
        tracing::debug!("[ChatExpander] Phase {phase} — resetting chat bar state");
        close_chat(&mut st);
    }
}

unsafe extern "system" fn find_valorant_enum(hwnd: HWND, lparam: LPARAM) -> BOOL {
    let mut pid = 0u32;
    GetWindowThreadProcessId(hwnd, Some(&mut pid));
    if pid != 0 && classify_pid(pid, hwnd) == FG_VALORANT {
        let out = lparam.0 as *mut HWND;
        unsafe {
            *out = hwnd;
        }
        return BOOL(0);
    }
    BOOL(1)
}

fn valorant_hwnd() -> Option<HWND> {
    let stored = LAST_VAL_HWND.load(Ordering::Relaxed);
    if stored != 0 {
        let hwnd = HWND(stored as *mut core::ffi::c_void);
        unsafe {
            if IsWindow(hwnd).as_bool() {
                return Some(hwnd);
            }
        }
    }
    let mut found = HWND::default();
    unsafe {
        let _ = EnumWindows(Some(find_valorant_enum), LPARAM(&mut found as *mut HWND as isize));
    }
    if found.0.is_null() {
        None
    } else {
        LAST_VAL_HWND.store(found.0 as usize, Ordering::Relaxed);
        Some(found)
    }
}

fn is_foreground(hwnd: HWND) -> bool {
    unsafe { GetForegroundWindow() == hwnd }
}

fn focus_valorant(hwnd: HWND) -> bool {
    unsafe {
        let _ = AllowSetForegroundWindow(u32::MAX);
        let mut pid = 0u32;
        let val_tid = GetWindowThreadProcessId(hwnd, Some(&mut pid));
        let our_tid = GetCurrentThreadId();
        if val_tid != 0 && val_tid != our_tid {
            let _ = AttachThreadInput(our_tid, val_tid, true);
            let _ = ShowWindow(hwnd, SW_RESTORE);
            let ok = SetForegroundWindow(hwnd).as_bool();
            let _ = AttachThreadInput(our_tid, val_tid, false);
            ok || is_foreground(hwnd)
        } else {
            let _ = ShowWindow(hwnd, SW_RESTORE);
            SetForegroundWindow(hwnd).as_bool() || is_foreground(hwnd)
        }
    }
}

fn ensure_valorant_focused(hwnd: HWND) -> bool {
    for attempt in 0..4 {
        if is_foreground(hwnd) || focus_valorant(hwnd) {
            std::thread::sleep(Duration::from_millis(if attempt == 0 { 180 } else { 80 }));
            if is_foreground(hwnd) {
                return true;
            }
        } else {
            std::thread::sleep(Duration::from_millis(80));
        }
    }
    is_foreground(hwnd)
}

fn chat_line_has(expected: &str) -> bool {
    let Some(got) = copy_chat_line() else {
        return false;
    };
    let want = expected.trim();
    let got = got.trim();
    !want.is_empty() && (got == want || got.ends_with(want))
}

/// Paste into the open game chat bar and confirm the line is actually there.
/// Valorant often ignores Ctrl+V if the widget is still opening — we retry
/// instead of hitting Enter on an empty box (which leaves chat open, no send).
fn fill_game_chat_line(text: &str) -> bool {
    for attempt in 0..3 {
        send_vk(VK_CONTROL, true);
        std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));
        tap_key(VK_A);
        std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));
        send_vk(VK_CONTROL, false);
        std::thread::sleep(Duration::from_millis(AFTER_CLEAR_MS));

        if set_clipboard_text(text) {
            paste_clipboard();
        } else {
            tracing::warn!("[live_chat] clipboard busy — unicode fallback");
            send_unicode_string_slow(text);
            std::thread::sleep(Duration::from_millis(AFTER_PASTE_MS));
        }
        std::thread::sleep(Duration::from_millis(80 + paste_settle_extra(text)));
        if chat_line_has(text) {
            return true;
        }
        tracing::warn!("[live_chat] paste missed chat bar (attempt {})", attempt + 1);
        std::thread::sleep(Duration::from_millis(160));
    }
    false
}

/// Send a LIVE line through Valorant's own chat bar (lobby / range / match).
///
/// The Riot Client HTTP API is a different XMPP resource and is usually not
/// in the game MUC, which is why `/chat/v6` send 404s in menus and range.
pub fn send_from_overlay(channel: &str, text: &str) -> Result<(), String> {
    let text = text.trim();
    if text.is_empty() {
        return Err("Empty message".into());
    }
    let hwnd = valorant_hwnd().ok_or_else(|| "Valorant window not found".to_string())?;
    {
        let mut st = STATE.lock();
        st.injecting = true;
        st.abort_injection = false;
        st.suppress_enter_until_ms = now_ms().saturating_add(ENTER_SUPPRESS_MS + 2_400);
    }
    let _guard = InjectingGuard;

    if !ensure_valorant_focused(hwnd) {
        tracing::warn!("[live_chat] Valorant not foreground — sending keys anyway");
    }

    let all_chat = channel == "all";
    if all_chat {
        send_vk(VK_SHIFT, true);
        std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));
        tap_key(VK_RETURN);
        std::thread::sleep(Duration::from_millis(CTRL_CHORD_GAP_MS));
        send_vk(VK_SHIFT, false);
    } else {
        tap_key(VK_RETURN);
    }
    // Widget needs a beat after Enter or the paste lands on a closed bar.
    std::thread::sleep(Duration::from_millis(380));

    let prev = get_clipboard_text();
    let filled = fill_game_chat_line(text);
    if !filled {
        if let Some(prev) = prev {
            let _ = set_clipboard_text(&prev);
        }
        {
            let mut st = STATE.lock();
            st.injecting = false;
            st.chat_open = true;
            st.buffer.clear();
            st.last_activity_ms = now_ms();
            st.suppress_enter_until_ms = now_ms().saturating_add(200);
        }
        tracing::warn!("[live_chat] abort send — line never appeared in game chat");
        return Err("Game chat did not accept the line".into());
    }
    std::thread::sleep(Duration::from_millis(BEFORE_SEND_ENTER_MS));
    tap_key(VK_RETURN);
    std::thread::sleep(Duration::from_millis(AFTER_SEND_ENTER_MS));
    if let Some(prev) = prev {
        let _ = set_clipboard_text(&prev);
    }
    {
        let mut st = STATE.lock();
        st.injecting = false;
        st.chat_open = true;
        st.buffer.clear();
        st.last_activity_ms = now_ms();
        st.suppress_enter_until_ms = now_ms().saturating_add(200);
    }
    tracing::info!("[live_chat] injected channel={channel} chars={}", text.chars().count());
    Ok(())
}


#[cfg(test)]
mod tests {
    use super::{
        classify_focus, key_to_char_us, needs_reclassify, pick_expand_source, Focus, FG_NEUTRAL,
        FG_OTHER, FG_VALORANT,
    };


    #[test]
    fn prefers_turkish_clipboard_over_ascii_buffer() {
        let src = pick_expand_source("gnaydn <3", Some("günaydın <3"), None);
        assert_eq!(src, "günaydın <3");
    }

    #[test]
    fn prefers_decoded_keys_when_copy_fails() {
        let src = pick_expand_source("ho; geldin <3", None, Some("hoş geldin <3"));
        assert_eq!(src, "hoş geldin <3");
    }

    #[test]
    fn ignores_stale_clipboard_without_shortcut() {
        let src = pick_expand_source("merhaba <3", Some("unrelated copied text"), None);
        assert_eq!(src, "merhaba <3");
    }

    #[test]
    fn ignores_empty_or_huge_copy() {
        assert_eq!(pick_expand_source("sa <3", Some(""), None), "sa <3");
        let huge = "a <3 ".repeat(200);
        assert_eq!(pick_expand_source("a <3", Some(&huge), None), "a <3");
    }

    #[test]
    fn decoded_beats_mangled_buffer_when_both_expand() {
        let src = pick_expand_source("Nasilsin <3 kanka", None, Some("Nasılsın <3 kanka"));
        assert_eq!(src, "Nasılsın <3 kanka");
    }

    #[test]
    fn clipboard_colon_d_beats_us_mapped_greater_d() {
        // TR-Q `:D` copied from the game vs US-QWERTY hook buffer `>D`.
        let src = pick_expand_source(">D", Some(":D"), None);
        assert_eq!(src, ":D");
        let src = pick_expand_source("gg >D", Some("gg :D"), Some("gg :D"));
        assert_eq!(src, "gg :D");
    }

    #[test]
    fn us_layout_maps_shift_period_to_greater_than() {
        // Documents the US fallback that used to corrupt TR-Q `:`.
        assert_eq!(key_to_char_us(0xBE, true), Some('>'));
        assert_eq!(key_to_char_us(0xBE, false), Some('.'));
        assert_eq!(key_to_char_us(0xBA, true), Some(':'));
        assert_eq!(key_to_char_us(0xE2, true), Some('>'));
        assert_eq!(key_to_char_us(0xE2, false), Some('<'));
    }


    #[test]
    fn exclusive_fullscreen_null_hwnd_keeps_valorant() {
        assert_eq!(
            classify_focus(0, 4242, FG_VALORANT),
            Focus::Valorant
        );
    }

    #[test]
    fn exclusive_fullscreen_null_hwnd_does_not_look_like_other_app() {
        // Overlay was last classified, then the game went exclusive-fullscreen.
        // Other would close the bar after 400ms; Unknown lets Enter re-open it.
        assert_eq!(classify_focus(0, 99, FG_OTHER), Focus::Unknown);
        assert_eq!(classify_focus(0, 99, FG_NEUTRAL), Focus::Unknown);
    }

    #[test]
    fn pid_mismatch_is_unknown_until_poller_catches_up() {
        assert_eq!(classify_focus(100, 200, FG_VALORANT), Focus::Unknown);
    }

    #[test]
    fn matching_pid_uses_kind() {
        assert_eq!(classify_focus(7, 7, FG_VALORANT), Focus::Valorant);
        assert_eq!(classify_focus(7, 7, FG_NEUTRAL), Focus::Unknown);
        assert_eq!(classify_focus(7, 7, FG_OTHER), Focus::Other);
    }

    #[test]
    fn reclassify_while_stuck_neutral_even_if_pid_unchanged() {
        assert!(needs_reclassify(10, 1, 10, 1, FG_NEUTRAL));
        assert!(needs_reclassify(10, 1, 10, 1, FG_OTHER));
        assert!(!needs_reclassify(10, 1, 10, 1, FG_VALORANT));
        assert!(needs_reclassify(11, 1, 10, 1, FG_VALORANT));
        assert!(needs_reclassify(10, 2, 10, 1, FG_VALORANT));
    }
}
